[target.aarch64-unknown-linux-musl]
linker = "aarch64-linux-gnu-gcc"
rustflags = "-Clink-self-contained=yes -Clinker=rust-lld"

[target.x86_64-unknown-linux-musl]
rustflags = "-Clink-self-contained=yes -Clinker=rust-lld"